---

- name: Create Mirabelle group
  become: true
  ansible.builtin.group:
    name: "{{ mirabelle_user }}"
    state: present

- name: Create Mirabelle user
  become: true
  ansible.builtin.user:
    name: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"

- name: Create Mirabelle directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"
  loop:
    - "{{ mirabelle_configuration_directory }}"
    - "{{ mirabelle_install_dir }}"
    - "{{ mirabelle_io_directory }}"
    - "{{ mirabelle_streams_directory }}"

- name: download Mirabelle
  become: true
  get_url:
    url: "{{ mirabelle_url }}"
    dest: "{{ mirabelle_install_dir }}/mirabelle.jar"
    owner: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"
    mode: '640'

- name: Template Mirabelle service
  become: true
  ansible.builtin.template:
    src: "{{ mirabelle_service_template }}"
    dest: "/etc/systemd/system/mirabelle.service"
    owner: "root"
    group: "root"
    mode: '0640'
  notify: systemd | reload

- name: Flush handlers
  meta: flush_handlers

- name: Template I/O configurations
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"
    mode: '0640'
  loop: "{{ mirabelle_io_templates }}"
  notify: mirabelle | restart

- name: Template Mirabelle configuration
  become: true
  ansible.builtin.template:
    src: "{{ mirabelle_configuration_template }}"
    dest: "{{ mirabelle_configuration_directory }}/mirabelle.edn"
    owner: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"
    mode: '0640'
  notify: mirabelle | restart

- name: Start Mirabelle
  become: true
  ansible.builtin.systemd:
    name: mirabelle
    state: started
    enabled: yes

- name: Flush handlers
  meta: flush_handlers

- name: Template streams configurations
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ mirabelle_user }}"
    group: "{{ mirabelle_user }}"
    mode: '0640'
  loop: "{{ mirabelle_streams_templates }}"
  notify: mirabelle | reload
  tags:
    - mirabelle_streams

